"""GraphQL payload rewriting for the mobilites-m WAF.

The WAF in front of ``otp.mobilites-m.fr`` blocks every JSON POST body that
contains the substring ``stop(id:`` (regex ``stop\\s*\\(``, case-insensitive,
applied to the decoded body). The public OTP2 server itself is fine.

This module rewrites a GraphQL query so that every ``stop(id: "...")`` field
becomes ``stop: stops(ids: ["..."])``, which the WAF allows and which is
semantically identical for OTP2. Because the original field is kept as a
GraphQL alias (``stop:``), the JSON response still has ``data.stop`` shaped as
a single object — as expected by consumers (openpublictransport sends
``{ stop(id:) { ... } }`` and expects ``data.stop`` to be an object).

The response of the rewritten query is ``data.stop`` = a *list* (possibly
containing ``null``), so :func:`reshape_response` converts it back to the
single-object shape the original query promised.

Supported argument forms (generated by aiohttp clients, all found in real
integrations):

* ``stop(id: "SEM:0501")``  — simple string literal
* ``stop(id:"SEM:0501")``   — no whitespace
* ``stop ( id: "X" )``      — arbitrary whitespace (the WAF regex tolerates
  it, but the literal substring ``stop(id:`` must not appear)

Not supported (rarely used by OTP2 clients): variables (``stop(id: $id)``),
block strings as id, nested parens inside the argument list. When a
``stop(`` occurrence cannot be rewritten safely the payload is rejected so
the proxy can return a clear error instead of forwarding a 403.
"""

from __future__ import annotations

import json
import re
from typing import Any

_WAF_TRIGGER = re.compile(r"stop\s*\(", re.IGNORECASE)
_STOP_FIELD = re.compile(r"\bstop\s*\(", re.IGNORECASE)

# Finds the id argument right after the opening paren of stop(...).
_ARG_START = re.compile(r"id\s*:\s*", re.IGNORECASE)


class RewriteError(ValueError):
    """Raised when a query cannot be rewritten safely."""


def _skip_ws(text: str, pos: int) -> int:
    while pos < len(text) and text[pos] in " \t\r\n,":
        pos += 1
    return pos


def mask_strings(text: str) -> str:
    """Return a copy of ``text`` where string literals are blanked out.

    Keeps offsets identical so matches on the masked text can be applied to
    the original. Unterminated strings blank to end-of-text.
    """
    out: list[str] = []
    pos = 0
    n = len(text)
    while pos < n:
        ch = text[pos]
        if ch == "\\" and pos + 1 < n and out and out[-1] != "\x00" * 0:
            # escaped char inside a string; handled by the string loop below
            pass
        if ch == '"':
            out.append('"')
            pos += 1
            while pos < n:
                c2 = text[pos]
                if c2 == "\\" and pos + 1 < n:
                    out.append(" ")
                    out.append(" ")
                    pos += 2
                    continue
                if c2 == '"':
                    out.append('"')
                    pos += 1
                    break
                out.append(" ")
                pos += 1
            continue
        out.append(ch)
        pos += 1
    return "".join(out)


def _read_string_literal(text: str, pos: int) -> tuple[str, int]:
    """Read a GraphQL string literal starting at ``pos`` (must be a quote).

    Returns (value, position_after_quote). Only regular quoted strings are
    supported; block strings raise RewriteError.
    """
    if text.startswith('"""', pos):
        raise RewriteError("block string ids are not supported")
    quote = text[pos]
    pos += 1
    out: list[str] = []
    while pos < len(text):
        ch = text[pos]
        if ch == "\\":
            nxt = text[pos + 1] if pos + 1 < len(text) else ""
            if nxt == "u" and pos + 5 < len(text):
                out.append(chr(int(text[pos + 2 : pos + 6], 16)))
                pos += 6
                continue
            out.append(nxt)
            pos += 2
            continue
        if ch == quote:
            return "".join(out), pos + 1
        out.append(ch)
        pos += 1
    raise RewriteError("unterminated string literal")


def _read_balanced(text: str, start: int) -> tuple[str, int]:
    """Return text[start:matching_paren] and the position after it.

    ``start`` must point at an opening paren.
    """
    depth = 0
    pos = start
    in_str = False
    quote = ""
    while pos < len(text):
        ch = text[pos]
        if in_str:
            if ch == "\\":
                pos += 2
                continue
            if ch == quote:
                in_str = False
        elif ch in "\"'":
            in_str = True
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return text[start : pos + 1], pos + 1
        pos += 1
    raise RewriteError("unbalanced parentheses")


def rewrite_query(query: str) -> str:
    """Rewrite every ``stop(id: "...")`` into ``stop: stops(ids: ["..."])``.

    Raises :class:`RewriteError` when a ``stop(`` occurrence cannot be
    handled (e.g. variables, block strings, unbalanced input).
    """
    masked = mask_strings(query)
    out: list[str] = []
    pos = 0
    while True:
        m = _STOP_FIELD.search(masked, pos)
        if not m:
            out.append(query[pos:])
            break
        field_start = m.start()
        out.append(query[pos:field_start])
        paren_open = m.end() - 1  # position of "("
        raw_args, after = _read_balanced(query, paren_open)
        inner = raw_args[1:-1]
        cursor = _skip_ws(inner, 0)
        idm = _ARG_START.match(inner, cursor)
        if idm is None or idm.start() != cursor:
            raise RewriteError(
                f"stop(...) without a literal id argument at offset {field_start}"
            )
        cursor = _skip_ws(inner, idm.end())
        if cursor >= len(inner) or inner[cursor] != '"':
            raise RewriteError(
                f"stop(id:) argument is not a string literal at offset {field_start}"
            )
        value, value_end = _read_string_literal(inner, cursor)
        tail = inner[value_end:].strip()
        if tail.startswith("#"):
            tail = ""
        if tail:
            raise RewriteError(
                f"unsupported extra arguments in stop(...) at offset {field_start}: {tail!r}"
            )
        out.append(f"stop: stops(ids: [{json.dumps(value)}])")
        pos = after
    return "".join(out)


def reshape_response(data: Any) -> Any:
    """Convert ``data.stop`` lists back into the object shape clients expect.

    OTP2 answers ``stops(ids: [x])`` with ``{"stops": [ {...} ]}``; because the
    rewrite aliases the field as ``stop``, responses arrive as
    ``{"stop": [...]}`` (or ``{"stop": [null]}`` for unknown ids). Original
    queries expect ``data.stop`` to be an object or null.
    """
    if not isinstance(data, dict):
        return data
    stop = data.get("stop")
    if isinstance(stop, list):
        data = dict(data)
        data["stop"] = stop[0] if stop else None
    return data


def rewrite_payload(body: str | dict) -> tuple[dict[str, Any], bool]:
    """Rewrite a JSON GraphQL request body.

    ``body`` may be a JSON string or an already-parsed dict. Handles both
    ``{"query": "..."}`` and ``{"query": "...", "variables": {...}}``.
    Returns ``(payload, rewritten)``.
    Raises :class:`RewriteError` for invalid bodies or unsafe queries.
    """
    if isinstance(body, (str, bytes)):
        try:
            payload = json.loads(body)
        except json.JSONDecodeError as err:
            raise RewriteError(f"invalid JSON body: {err}") from err
    else:
        payload = body
    if not isinstance(payload, dict) or not isinstance(payload.get("query"), str):
        raise RewriteError("body must be a JSON object with a string 'query'")
    query = payload["query"]
    if _WAF_TRIGGER.search(mask_strings(query)):
        payload = dict(payload)
        payload["query"] = rewrite_query(query)
        return payload, True
    return payload, False
